exclude:
  - bin
  - README.md
keep_files: [
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  css,
  images,
  img,
  index.html,
  js,
  pages,
  posts,
  theme.css,
  theme.js,
]
plugins:
  - jekyll-sitemap
