exclude:
  - bin
  - README.md
keep_files: [
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  css,
  images,
  img,
  index.html,
  js,
  pages,
  posts,
  robots.txt,
  sitemap.xml,
  theme.css,
  theme.js,
]
